

--1. Q1(a): Find the list of employees whose salary ranges between 2L to 3L.
--2. Q1(b): Write a query to retrieve the list of employees from the same city.
--3. Q1(c): Query to find the null values in the Employee table.
--4. Q2(a): Query to find the cumulative sum of employee’s salary.
--5. Q2(b): What’s the male and female employees ratio.
--6. Q2(c): Write a query to fetch 50% records from the Employee table.
--7. Q3: Query to fetch the employee’s salary but replace the LAST 2 digits with ‘XX’  
--8. Q4: Write a query to fetch even and odd rows from Employee table.
--9. Q5(a): Write a query to find all the Employee names whose name:
--   - Begin with ‘A’
--   - Contains ‘A’ alphabet at second place
--   - Contains ‘Y’ alphabet at second last place
--   - Ends with ‘L’ and contains 4 alphabets 
--   - Begins with ‘V’ and ends with ‘A’
--10. Q5(b): Write a query to find the list of Employee names which is:
--    - Starting with vowels (a, e, i, o, or u), without duplicates
--    - Ending with vowels (a, e, i, o, or u), without duplicates
--    - Starting & ending with vowels (a, e, i, o, or u), without duplicates
--11. Q6: Find Nth highest salary from employee table with and without using the TOP/LIMIT keywords.
--12. Q7(a): Write a query to find and remove duplicate records from a table.
--13. Q7(b): Query to retrieve the list of employees working in same project.
--14. Q8: Show the employee with the highest salary for each project.
--15. Q9: Query to find the total count of employees joined each year.
--16. Q10: Create 3 groups based on salary col, salary less than 1L is low, between 1-2L is medium and above 2L is High.
--17. BONUS: Query to pivot the data in the Employee table and retrieve the total salary for each city.
