--desc employees;
--Select * from employee;
--desc EmployeeDetail;
--Select * from EmployeeDetail;
--
--CREATE TABLE Employee (
--    EmpID INT NOT NULL,
--    EmpName VARCHAR2(255),  -- Specified maximum length
--    Gender CHAR(1),         -- Specified length for single character
--    Salary INT,
--    City VARCHAR2(20),      -- Used VARCHAR2 for variable character length
--    PRIMARY KEY (EmpID)     -- Added primary key constraint
--);
--
--INSERT INTO Employee (EmpID, EmpName, Gender, Salary, City) VALUES (1, 'Arjun', 'M', 75000, 'Pune');
--INSERT INTO Employee (EmpID, EmpName, Gender, Salary, City) VALUES (2, 'Ekadanta', 'M', 125000, 'Bangalore');
--INSERT INTO Employee (EmpID, EmpName, Gender, Salary, City) VALUES (3, 'Lalita', 'F', 150000, 'Mathura');
--INSERT INTO Employee (EmpID, EmpName, Gender, Salary, City) VALUES (4, 'Madhav', 'M', 250000, 'Delhi');
--INSERT INTO Employee (EmpID, EmpName, Gender, Salary, City) VALUES (5, 'Visakha', 'F', 120000, 'Mathura');
--
--
-- CREATE TABLE EmployeeDetail (
--    EmpID int NOT NULL,
--    Project Varchar(50),
--    EmpPosition Char(20),
--    DOJ date
--);
--
--INSERT INTO EmployeeDetail (EMPID, PROJECT, EMPPOSITION, DOJ) VALUES (1, 'P1', 'Executive', TO_DATE('2022-06-06', 'YYYY-MM-DD'));
--INSERT INTO EmployeeDetail (EMPID, PROJECT, EMPPOSITION, DOJ) VALUES (2, 'P2', 'Executive', TO_DATE('2022-06-06', 'YYYY-MM-DD'));
--INSERT INTO EmployeeDetail (EMPID, PROJECT, EMPPOSITION, DOJ) VALUES (3, 'P1', 'Lead', TO_DATE('2022-06-06', 'YYYY-MM-DD'));
--INSERT INTO EmployeeDetail (EMPID, PROJECT, EMPPOSITION, DOJ) VALUES (4, 'P3', 'Manager', TO_DATE('2022-06-06', 'YYYY-MM-DD'));
--INSERT INTO EmployeeDetail (EMPID, PROJECT, EMPPOSITION, DOJ) VALUES (5, 'P2', 'Manager', TO_DATE('2022-06-06', 'YYYY-MM-DD'));

--insert into emp1(ADDRESS,RENGO,PHONENUMBER) values('kotwa', 12,1423);

--desc employee
--desc employeedetail
--desc emp1
--
--select * from employee;
--select * from employees;
--select * from employeedetail;
--select * from emp1;
--
--DELETE FROM employeedetail
--WHERE EmpID IN (6, 7, 8, 9, 10, 11, 12);
--
--COMMIT;
--ROLLBACK;
--
--CREATE TABLE emptest (
--    emp_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    first_name VARCHAR2(50),
--    last_name VARCHAR2(50),
--    email VARCHAR2(100),
--    phone_number VARCHAR2(15),
--    hire_date DATE,
--    job_id VARCHAR2(10),
--    salary NUMBER(8, 2),
--    manager_id NUMBER,
--    department_id NUMBER
--);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('John', 'Smith', 'john.smith@example.com', '1234567890', TO_DATE('2023-01-01', 'YYYY-MM-DD'), 'DEV', 60000, 101, 1);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Jane', 'Doe', 'jane.doe@example.com', '1234567891', TO_DATE('2023-01-02', 'YYYY-MM-DD'), 'DEV', 65000, 102, 1);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Alice', 'Johnson', 'alice.johnson@example.com', '1234567892', TO_DATE('2023-01-03', 'YYYY-MM-DD'), 'HR', 62000, 103, 2);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Bob', 'Williams', 'bob.williams@example.com', '1234567893', TO_DATE('2023-01-04', 'YYYY-MM-DD'), 'HR', 61000, 103, 2);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Charlie', 'Brown', 'charlie.brown@example.com', '1234567894', TO_DATE('2023-01-05', 'YYYY-MM-DD'), 'DEV', 67000, 102, 1);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Dave', 'Wilson', 'dave.wilson@example.com', '1234567895', TO_DATE('2023-01-06', 'YYYY-MM-DD'), 'DEV', 64000, 101, 1);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Eve', 'Davis', 'eve.davis@example.com', '1234567896', TO_DATE('2023-01-07', 'YYYY-MM-DD'), 'HR', 63000, 103, 2);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Frank', 'Miller', 'frank.miller@example.com', '1234567897', TO_DATE('2023-01-08', 'YYYY-MM-DD'), 'DEV', 62000, 102, 1);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Grace', 'Garcia', 'grace.garcia@example.com', '1234567898', TO_DATE('2023-01-09', 'YYYY-MM-DD'), 'HR', 61000, 103, 2);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Hank', 'Martinez', 'hank.martinez@example.com', '1234567899', TO_DATE('2023-01-10', 'YYYY-MM-DD'), 'DEV', 65000, 102, 1);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Ivy', 'Rodriguez', 'ivy.rodriguez@example.com', '1234567800', TO_DATE('2023-01-11', 'YYYY-MM-DD'), 'DEV', 66000, 101, 1);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Jack', 'Martinez', 'jack.martinez@example.com', '1234567801', TO_DATE('2023-01-12', 'YYYY-MM-DD'), 'HR', 64000, 103, 2);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Karen', 'Lee', 'karen.lee@example.com', '1234567802', TO_DATE('2023-01-13', 'YYYY-MM-DD'), 'HR', 63000, 103, 2);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Larry', 'Clark', 'larry.clark@example.com', '1234567803', TO_DATE('2023-01-14', 'YYYY-MM-DD'), 'DEV', 67000, 102, 1);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Megan', 'Lopez', 'megan.lopez@example.com', '1234567804', TO_DATE('2023-01-15', 'YYYY-MM-DD'), 'HR', 62000, 103, 2);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Nina', 'White', 'nina.white@example.com', '1234567805', TO_DATE('2023-01-16', 'YYYY-MM-DD'), 'DEV', 65000, 101, 1);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Oscar', 'Harris', 'oscar.harris@example.com', '1234567806', TO_DATE('2023-01-17', 'YYYY-MM-DD'), 'HR', 61000, 103, 2);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Paul', 'Thompson', 'paul.thompson@example.com', '1234567807', TO_DATE('2023-01-18', 'YYYY-MM-DD'), 'DEV', 64000, 102, 1);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Quincy', 'Martinez', 'quincy.martinez@example.com', '1234567808', TO_DATE('2023-01-19', 'YYYY-MM-DD'), 'HR', 63000, 103, 2);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Rachel', 'White', 'rachel.white@example.com', '1234567809', TO_DATE('2023-01-20', 'YYYY-MM-DD'), 'DEV', 62000, 101, 1);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Steve', 'Young', 'steve.young@example.com', '1234567810', TO_DATE('2023-01-21', 'YYYY-MM-DD'), 'HR', 61000, 103, 2);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Tina', 'Scott', 'tina.scott@example.com', '1234567811', TO_DATE('2023-01-22', 'YYYY-MM-DD'), 'DEV', 65000, 102, 1);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Uma', 'Hill', 'uma.hill@example.com', '1234567812', TO_DATE('2023-01-23', 'YYYY-MM-DD'), 'HR', 66000, 103, 2);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Vince', 'Green', 'vince.green@example.com', '1234567813', TO_DATE('2023-01-24', 'YYYY-MM-DD'), 'DEV', 67000, 101, 1);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Wendy', 'Adams', 'wendy.adams@example.com', '1234567814', TO_DATE('2023-01-25', 'YYYY-MM-DD'), 'HR', 62000, 103, 2);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Xavier', 'Baker', 'xavier.baker@example.com', '1234567815', TO_DATE('2023-01-26', 'YYYY-MM-DD'), 'DEV', 63000, 102, 1);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Yolanda', 'Gonzalez', 'yolanda.gonzalez@example.com', '1234567816', TO_DATE('2023-01-27', 'YYYY-MM-DD'), 'HR', 64000, 103, 2);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Zach', 'Nelson', 'zach.nelson@example.com', '1234567817', TO_DATE('2023-01-28', 'YYYY-MM-DD'), 'DEV', 65000, 101, 1);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Aaron', 'Carter', 'aaron.carter@example.com', '1234567818', TO_DATE('2023-01-29', 'YYYY-MM-DD'), 'HR', 66000, 103, 2);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Bella', 'Murphy', 'bella.murphy@example.com', '1234567819', TO_DATE('2023-01-30', 'YYYY-MM-DD'), 'DEV', 67000, 102, 1);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Aalam', 'Kotwa', 'aalam.murphy@example.com', '9958993613', TO_DATE('2023-01-30', 'YYYY-MM-DD'), 'DEV', 68000, 102, 1);
--
--INSERT INTO emptest (first_name, last_name, email, phone_number, hire_date, job_id, salary, manager_id, department_id)
--VALUES ('Aalam', 'Kotwa', 'holaji.murphy@example.com', '9958993612', TO_DATE('2023-01-30', 'YYYY-MM-DD'), 'DEV', 69000, 102, 1);
--
--
--desc emptest;
--select count (emp_id) from emptest;
--select * from emptest;
--
--
--CREATE TABLE department (
--    department_id NUMBER PRIMARY KEY,
--    department_name VARCHAR2(50),
--    location VARCHAR2(100)
--);
--
--INSERT INTO department (department_id, department_name, location) VALUES (1, 'Development', 'New York');
--INSERT INTO department (department_id, department_name, location) VALUES (2, 'Human Resources', 'Chicago');
--INSERT INTO department (department_id, department_name, location) VALUES (3, 'Sales', 'San Francisco');
--INSERT INTO department (department_id, department_name, location) VALUES (4, 'Marketing', 'Los Angeles');
--INSERT INTO department (department_id, department_name, location) VALUES (5, 'Finance', 'Houston');
--INSERT INTO department (department_id, department_name, location) VALUES (6, 'IT', 'Austin');
--INSERT INTO department (department_id, department_name, location) VALUES (7, 'Support', 'Dallas');
--INSERT INTO department (department_id, department_name, location) VALUES (8, 'Operations', 'San Diego');
--INSERT INTO department (department_id, department_name, location) VALUES (9, 'Research', 'Boston');
--INSERT INTO department (department_id, department_name, location) VALUES (10, 'Engineering', 'Seattle');
--INSERT INTO department (department_id, department_name, location) VALUES (11, 'Procurement', 'Miami');
--INSERT INTO department (department_id, department_name, location) VALUES (12, 'Legal', 'Washington');
--INSERT INTO department (department_id, department_name, location) VALUES (13, 'Compliance', 'Denver');
--INSERT INTO department (department_id, department_name, location) VALUES (14, 'Quality Assurance', 'Portland');
--INSERT INTO department (department_id, department_name, location) VALUES (15, 'Business Development', 'Atlanta');
--INSERT INTO department (department_id, department_name, location) VALUES (16, 'Corporate Affairs', 'Orlando');
--INSERT INTO department (department_id, department_name, location) VALUES (17, 'Public Relations', 'Charlotte');
--INSERT INTO department (department_id, department_name, location) VALUES (18, 'Investor Relations', 'San Antonio');
--INSERT INTO department (department_id, department_name, location) VALUES (19, 'Customer Service', 'Phoenix');
--INSERT INTO department (department_id, department_name, location) VALUES (20, 'Training', 'Philadelphia');
--INSERT INTO department (department_id, department_name, location) VALUES (21, 'Executive', 'Las Vegas');
--INSERT INTO department (department_id, department_name, location) VALUES (22, 'Security', 'Minneapolis');
--INSERT INTO department (department_id, department_name, location) VALUES (23, 'Administration', 'Kansas City');
--INSERT INTO department (department_id, department_name, location) VALUES (24, 'Logistics', 'Cleveland');
--INSERT INTO department (department_id, department_name, location) VALUES (25, 'Transportation', 'Detroit');
--INSERT INTO department (department_id, department_name, location) VALUES (26, 'Facilities', 'Indianapolis');
--INSERT INTO department (department_id, department_name, location) VALUES (27, 'Manufacturing', 'Columbus');
--INSERT INTO department (department_id, department_name, location) VALUES (28, 'Production', 'Nashville');
--INSERT INTO department (department_id, department_name, location) VALUES (29, 'Distribution', 'Milwaukee');
--INSERT INTO department (department_id, department_name, location) VALUES (30, 'Purchasing', 'New Orleans');
--INSERT INTO department (department_id, department_name, location) VALUES (31, 'Purchasing', 'New Orleans');
--INSERT INTO department (department_id, department_name, location) VALUES (32, 'Purchasing', 'New Orleans');

desc department;
select count(department_id) from department;
select * from department;
select * from emptest;

select first_name, salary from emptest where salary between 60000 and 65000;

--Write a query to retrieve the list of employees from the same city.
--SELECT *
--FROM department
--WHERE location IN (
--    SELECT location
--    FROM department
--    GROUP BY location
--    HAVING COUNT(*) > 1
--);
--
--SELECT d1.*
--FROM department d1
--JOIN (
--    SELECT location
--    FROM department
--    GROUP BY location
--    HAVING COUNT(*) > 1
--) d2
--ON d1.location = d2.location;
--
--
--SELECT *
--FROM department d1
--WHERE EXISTS (
--    SELECT 1
--    FROM department d2
--    WHERE d1.location = d2.location
--    GROUP BY location
--    HAVING COUNT(*) > 1
--);


select count(*) from employee;
select * from employee

select city, count(*) from employee group by city having count(*)>0;

SELECT City, COUNT(*)
FROM Employee
GROUP BY City
HAVING COUNT(*) > 1;


CREATE TABLE EmployeeDetails_learn (
    EmpID INTEGER,
    FirstName VARCHAR2(50),
    LastName VARCHAR2(50),
    DateOfBirth DATE,
    DateOfJoining TIMESTAMP,
    EmployeeNumber NUMBER(10, 2),
    Salary NUMBER(15, 2),
    Bonus FLOAT(10),
    PerformanceRating FLOAT(2),
    DepartmentID INTEGER,
    YearsOfExperience INTEGER,
    Address VARCHAR2(255),
    PhoneNumber VARCHAR2(15),
    Email VARCHAR2(100)
);

INSERT INTO EmployeeDetails_learn (
    EmpID, FirstName, LastName, DateOfBirth, DateOfJoining, EmployeeNumber, 
    Salary, Bonus, PerformanceRating, DepartmentID, YearsOfExperience, Address, 
    PhoneNumber, Email
) VALUES (
    1001, 'John', 'Doe', DATE '1980-05-23', TIMESTAMP '2010-06-01 09:00:00', 12345.67, 
    75000.50, 5000.75, 4.5, 101, 15, '1234 Elm Street, Springfield', 
    '1234567890', 'john.doe@example.com'
);

select * from employees;
select * from employee;

select * from employees 
join employee e on e.empid = empid;

select count(salary) from employees;

select * from employees 
full join employee e on e.empid = e.empid;

select salary from employees where salary between 10000 and 40000;

